-- 添加用户扩展字段
-- 执行时间: 2025-01-16

ALTER TABLE users 
ADD COLUMN IF NOT EXISTS nickname VARCHAR(100) COMMENT '昵称',
ADD COLUMN IF NOT EXISTS phone VARCHAR(20) COMMENT '手机号',
ADD COLUMN IF NOT EXISTS email VARCHAR(100) COMMENT '邮箱',
ADD COLUMN IF NOT EXISTS signature VARCHAR(200) COMMENT '个性签名',
ADD COLUMN IF NOT EXISTS created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间';

-- 添加角色字段
ALTER TABLE users
ADD COLUMN IF NOT EXISTS role VARCHAR(20) DEFAULT 'user' NOT NULL COMMENT '用户角色: admin 或 user';

-- 为已存在的用户设置默认创建时间
UPDATE users SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
